ALTER TABLE VS_COOK_TEST.EXPORT_STATUS_LOG
 DROP PRIMARY KEY CASCADE;

DROP TABLE VS_COOK_TEST.EXPORT_STATUS_LOG CASCADE CONSTRAINTS;

CREATE TABLE VS_COOK_TEST.EXPORT_STATUS_LOG
(
  ROWS_PROCESSED  NUMBER,
  ROWS_TOTAL      NUMBER,
  EXPORT_ID       NUMBER,
  STATUS          VARCHAR2(50 BYTE)             DEFAULT NULL,
  ERROR_MSG       VARCHAR2(500 BYTE),
  EXPORT_NAME     VARCHAR2(500 BYTE),
  EXPORT_START    DATE                          DEFAULT SYSDATE,
  ACTIVITY_DATE   DATE                          DEFAULT SYSDATE,
  USERNAME        VARCHAR2(50 BYTE)             DEFAULT USER,
  COMMENTS        VARCHAR2(4000 BYTE)
)
TABLESPACE VEMACS_DATA
PCTUSED    0
PCTFREE    10
INITRANS   1
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING;


CREATE UNIQUE INDEX VS_COOK_TEST.NG_EXPORT_LOG_PK ON VS_COOK_TEST.EXPORT_STATUS_LOG
(EXPORT_ID, EXPORT_NAME)
LOGGING
TABLESPACE VEMACS_DATA
PCTFREE    10
INITRANS   2
MAXTRANS   255
STORAGE    (
            INITIAL          64K
            NEXT             1M
            MINEXTENTS       1
            MAXEXTENTS       UNLIMITED
            PCTINCREASE      0
            BUFFER_POOL      DEFAULT
           )
NOPARALLEL;


ALTER TABLE VS_COOK_TEST.EXPORT_STATUS_LOG ADD (
  CONSTRAINT NG_EXPORT_LOG_PK
  PRIMARY KEY
  (EXPORT_ID, EXPORT_NAME)
  USING INDEX VS_COOK_TEST.NG_EXPORT_LOG_PK);
